runtime: nodejs18

handlers:
  # Handle custom share links, rewriting them to the main application
  - url: /sheet/.*
    static_files: index.html
    upload: index.html

  # Serve static files directly if found
  - url: /(.*\..+)$
    static_files: \1
    upload: (.*\..+)$

  # Catch-all for React Router/SPA routing
  - url: /.*
    static_files: index.html
    upload: index.html