#!/bin/sh

# Create the env-config.js file in the React app webroot
cat <<EOF > /var/www/app/env-config.js
window._env_ = {
  API_KEY: "${API_KEY}",
  GEMINI_API_KEY: "${GEMINI_API_KEY}",
  VITE_FIREBASE_API_KEY: "${VITE_FIREBASE_API_KEY}",
  VITE_FIREBASE_AUTH_DOMAIN: "${VITE_FIREBASE_AUTH_DOMAIN}",
  VITE_FIREBASE_PROJECT_ID: "${VITE_FIREBASE_PROJECT_ID}",
  VITE_FIREBASE_STORAGE_BUCKET: "${VITE_FIREBASE_STORAGE_BUCKET}",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "${VITE_FIREBASE_MESSAGING_SENDER_ID}",
  VITE_FIREBASE_APP_ID: "${VITE_FIREBASE_APP_ID}",
  VITE_FIREBASE_MEASUREMENT_ID: "${VITE_FIREBASE_MEASUREMENT_ID}",
  VITE_RECAPTCHA_SITE_KEY: "${VITE_RECAPTCHA_SITE_KEY}",
  VITE_STRIPE_PRO_MONTHLY_PRICE_ID: "${VITE_STRIPE_PRO_MONTHLY_PRICE_ID}",
  VITE_STRIPE_PRO_ANNUAL_PRICE_ID: "${VITE_STRIPE_PRO_ANNUAL_PRICE_ID}",
  LOCAL_ARCHITECT_URL: "${LOCAL_ARCHITECT_URL}",
  LOCAL_ARCHITECT_MODEL: "${LOCAL_ARCHITECT_MODEL}"
};
EOF

# Start nginx
exec nginx -g 'daemon off;'
